on:
  schedule:
    - cron: '04 05 14 05 *'
  workflow_dispatch:

jobs:
  discord_message:
    name: Discord message
    runs-on: ubuntu-latest
    steps:
      - name: send message
        run: |
           curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"Всім привіт! Завтра, 31.07, о 13:30, у нас ретроспектива 13-го спринта.\"}" https://discord.com/api/webhooks/${{ secrets.DISCORD_ID }}/${{ secrets.DISCORD_TOKEN }}
           echo -H "Content-Type: application/json" -X POST -d "{\"content\": \"Всім привіт! Ну от і добрались - наступний після поточного спрінта - командний. Багатьом наче сподобалось 😀, тому збираємо охочих ще раз попрактикуватись у командній роботі. Хто долучається до командного виконання - лайкніть це повідомлення до 16:00 години вівторка, 14.03.\"}" https://discord.com/api/webhooks/${{ secrets.DISCORD_ID }}/${{ secrets.DISCORD_TOKEN }}
