on:
  schedule:
    - cron: '04 05 14 05 *'
  workflow_dispatch:

jobs:
  discord_message:
    name: Discord message
    runs-on: ubuntu-latest
    steps:
      - name: send message
        run: |
           curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"Привіт всім! Завтра, 03.08, о 12:30, у нас ретроспектива 8-го спринта.\"}" https://discord.com/api/webhooks/${{ secrets.DISCORD_ID }}/${{ secrets.DISCORD_TOKEN }}
          
