on:
  schedule:
    - cron: '47 4 30 12 *'
  workflow_dispatch:

jobs:
  discord_message:
    name: Discord message
    runs-on: ubuntu-latest
    steps:
      - name: send message
        run: |
           curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"Доброго ранку марафонці! Сьогодні о 13:00 відбудеться ретроспектива 10-го спрінта.\"}" https://discord.com/api/webhooks/${{ secrets.DISCORD_ID }}/${{ secrets.DISCORD_TOKEN }}
