on:
  schedule:
    - cron: '05 06 12 03 *'
  workflow_dispatch:

jobs:
  discord_message:
    name: Discord message
    runs-on: ubuntu-latest
    steps:
      - name: send message
        run: |
           echo -H "Content-Type: application/json" -X POST -d "{\"content\": \"Доброго дня! Ретроспективу 13-го спринта ми проведемо в понеділок, 06.03, о 13:30.\"}" https://discord.com/api/webhooks/${{ secrets.DISCORD_ID }}/${{ secrets.DISCORD_TOKEN }}
           curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"Всім привіт! Ну от і добрались - наступний після поточного спрінта - командний. Багатьом наче сподобалось 😀, тому збираємо охочих ще раз попрактикуватись у командній роботі. Хто долучається до командного виконання - лайкніть це повідомлення до 16:00 години вівторка, 14.03.\"}" https://discord.com/api/webhooks/${{ secrets.DISCORD_ID }}/${{ secrets.DISCORD_TOKEN }}
