on:
  schedule:
    - cron: '51 04 23 04 *'
  workflow_dispatch:

jobs:
  discord_message:
    name: Discord message
    runs-on: ubuntu-latest
    steps:
      - name: send message
        run: |
           curl -H "Content-Type: application/json" -X PATCH -d "{\"content\": \"Доброго дня! Ретроспективу 7-го спринта ми проведемо в понеділок, 24.04, о 13:00.\"}" https://discord.com/api/webhooks/${{ secrets.DISCORD_ID }}/${{ secrets.DISCORD_TOKEN }}/1099559277787611281
           echo -H "Content-Type: application/json" -X POST -d "{\"content\": \"Доброго дня! Ретроспективу 13-го спринта ми проведемо в понеділок, 24.04, о 13:00.\"}" https://discord.com/api/webhooks/${{ secrets.DISCORD_ID }}/${{ secrets.DISCORD_TOKEN }}
           echo -H "Content-Type: application/json" -X POST -d "{\"content\": \"Всім привіт! Ну от і добрались - наступний після поточного спрінта - командний. Багатьом наче сподобалось 😀, тому збираємо охочих ще раз попрактикуватись у командній роботі. Хто долучається до командного виконання - лайкніть це повідомлення до 16:00 години вівторка, 14.03.\"}" https://discord.com/api/webhooks/${{ secrets.DISCORD_ID }}/${{ secrets.DISCORD_TOKEN }}
