on:
  schedule:
    - cron: '04 09 25 09 *'
  workflow_dispatch:

jobs:
  discord_message:
    name: Discord message
    runs-on: ubuntu-latest
    steps:
      - name: send message
        run: |
           curl  -H "Content-Type: application/json" -X POST -d "{\"content\": \"${{ vars.DISCORD_TEXT }}\" }" https://discord.com/api/webhooks/${{ secrets.DISCORD_ID }}/${{ secrets.DISCORD_TOKEN }}
          
