on:
  schedule:
    - cron: '05 06 05 02 *'
  workflow_dispatch:

jobs:
  discord_message:
    name: Discord message
    runs-on: ubuntu-latest
    steps:
      - name: send message
        run: |
           curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"Доброго дня! Ретроспективу 5-го спринта ми проведемо в понеділок, 06.02, о 14:00.\"}" https://discord.com/api/webhooks/${{ secrets.DISCORD_ID }}/${{ secrets.DISCORD_TOKEN }}
