on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '45 6 8 4 *'

jobs:
  discord_message:
    name: Discord message
    runs-on: ubuntu-latest
    steps:
      - name: send message
        run: |
          curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"Сьогодні о 13:00 проведемо ретроспективу 6-го спрінта\"}" https://discord.com/api/webhooks/${{ secrets.DISCORD_ID }}/${{ secrets.DISCORD_TOKEN }}
